import Footer from "@/sections/Footer";
import Navbar from "@/sections/Navbar";
import Providers from "@/utils/provider";
import type { Metadata } from "next";
import { Poppins, Public_Sans } from "next/font/google";
import { Suspense } from "react";
import "../style/globals.css";
import Loading from "./loading";

const publicSans = Public_Sans({ subsets: ["latin"] });

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${publicSans.className} ${poppins.className} bg-[#FAFAFA]`}
      >
        <Providers>
          <Navbar />
          <Suspense fallback={<Loading />}>
            <main className="min-h-screen container px-5 py-16 mx-auto ">
              {children}
            </main>
          </Suspense>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
